[tool.black]
line-length = 79
target-version = ["py38", "py39"]

[tool.isort]
ensure_newline_before_comments = true
line_length = 79
multi_line_output = 3
include_trailing_comma = true
skip_glob = ["docs/*", "migrations/*", "admin_dashboard/static/js/*", "*.egg-info"]
